# Generated by Django 4.2.13 on 2024-06-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="email address"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("content", models.CharField(max_length=1000, verbose_name="내용")),
                ("price", models.CharField(max_length=255, verbose_name="가격")),
                ("region", models.CharField(max_length=100, verbose_name="지역")),
                ("address", models.CharField(max_length=255, verbose_name="주소")),
                ("size", models.CharField(max_length=100, verbose_name="크기")),
                ("direction", models.CharField(max_length=100, verbose_name="방향")),
                ("availability", models.CharField(max_length=100, verbose_name="입주시기")),
                ("floor", models.CharField(max_length=100, verbose_name="몇층")),
                ("apart", models.CharField(max_length=255, verbose_name="아파트")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.post"
                    ),
                ),
            ],
        ),
    ]
