# Generated by Django 3.2.23 on 2024-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('mager_info', models.CharField(max_length=500)),
                ('transaction_info', models.TextField(verbose_name='거래정보')),
                ('management_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='공용관리비')),
                ('individual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='개별사용료')),
                ('mortgage', models.BooleanField(default=False, verbose_name='융자여부')),
            ],
        ),
        migrations.CreateModel(
            name='JsonDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
