# Generated by Django 4.2.13 on 2024-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0002_pdffile_remove_document_individual_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffile",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
